{% set name = "FIt-SNE" %}
{% set version = "1.2.0" %}
{% set sha256 = "1b6a95c95660a977244e00528083d3a6f84a921ee597c6cab71f0fc6f39f72d6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/KlugerLab/FIt-SNE/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - fftw

test:
  commands:
    - command -v fast_tsne

about:
  home: https://github.com/KlugerLab/FIt-SNE
  license: Multiple
  license_file: LICENSE.txt
  license_family: OTHER
  summary: Fast Fourier Transform-accelerated Interpolation-based t-SNE (FIt-SNE)

extra:
  recipe-maintainers:
    - raivivek
    - dkobak
